// import { FaEye } from "react-icons/fa";

// const products = [
//     {
//       id: 1,
//       image: "images/product1.svg",
//       title: "The north coat",
//       price: 250,
//       rating: 65,
//       saleBadge: "40%",
//       heartIcon: <FaRegHeart />,
//       eyeIcon: <FaEye />,
//       priceStrikeThrough: 380,
//       color: "red",
//       padding: "px-4 py-1",
    
//     },
//     {
//       id: 2,
//       image: "images/product2.svg",
//       title: "Gucci duffle bag",
//       price: 960,
//       rating: 65,
//       saleBadge: "35%",
//       priceStrikeThrough: 1160,
//       heartIcon: <FaRegHeart />,
//       eyeIcon: <FaEye />,
//       color: "red",
//       padding: "px-4 py-1",
     
//     },
//     {
//       id: 3,
//       image: "images/product3.svg",
//       title: "RGB liquid CPU Cooler",
//       price: 160,
//       rating: 65,
//       saleBadge: "30%",
//       priceStrikeThrough: 170,
//       heartIcon: <FaRegHeart />,
//       eyeIcon: <FaEye />,
//       color: "red",
//       padding: "px-4 py-1",
      
//     },
//     {
//       id: 4,
//       image: "images/product4.svg",
//       title: "Small BookSelf",
//       price: 360,
//       rating: 65,
//       saleBadge: "25%",
//       heartIcon: <FaRegHeart />,
//       eyeIcon: <FaEye />,
//       color: "red",
//       padding: "px-4 py-1",
     
//     },
//     {
//       id: 5,
//       image: "images/wishlist5.svg",
//       title: "Casual T-Shirt",
//       price: 960,
//       rating: 65,
//       saleBadge: "30%",
//       heartIcon: <FaRegHeart />,
//       eyeIcon: <FaEye />,
//       priceStrikeThrough: 1160,
//       color: "red",
//       padding: "px-4 py-1",
      
//     },
//     {
//       id: 6,
//       image: "images/wishlist6.svg",
//       title: "Leather Wallet",
//       price: 1160,
//       rating: 65,
//       heartIcon: <FaRegHeart />,
//       eyeIcon: <FaEye />,
//       color: "blue",
//       padding: "px-4 py-1",
     
//     },
//     {
//       id: 7,
//       image: "images/wishlist7.svg",
//       title: "Sports Sunglasses",
//       price: 560,
//       rating: 65,
//       saleBadge: "Hot",
//       heartIcon: <FaRegHeart />,
//       eyeIcon: <FaEye />,
//       padding: "px-4 py-1",
     
//     },
//     {
//       id: 8,
//       image: "images/wishlist8.svg",
//       title: "Wireless Earbuds",
//       price: 200,
//       rating: 65,
//       heartIcon: <FaRegHeart />,
//       eyeIcon: <FaEye />,
//       color: "green",
//       padding: "px-4 py-1",
     
//     },
//     {
//       id: 9,
//       image: "images/Product-1.svg",
//       title: "The north coat",
//       price: 250,
//       rating: 65,
//       heartIcon: <FaRegHeart />,
//       eyeIcon: <FaEye />,
//       priceStrikeThrough: 380,
//       color: "red",
//       padding: "px-4 py-1",
    
//     },
//     {
//       id: 10,
//       image: "images/Product-2.svg",
//       title: "Gucci duffle bag",
//       price: 960,
//       rating: 65,
//       priceStrikeThrough: 1160,
//       heartIcon: <FaRegHeart />,
//       eyeIcon: <FaEye />,
//       color: "blue",
//       padding: "px-4 py-1",
     
//     },
//     {
//       id: 11,
//       image: "images/Product-3.svg",
//       title: "RGB liquid CPU Cooler",
//       price: 160,
//       rating: 65,
//       priceStrikeThrough: 170,
//       heartIcon: <FaRegHeart />,
//       eyeIcon: <FaEye />,
//       padding: "px-4 py-1",
      
//     },
//     {
//       id: 12,
//       image: "images/Product-4.svg",
//       title: "Small BookSelf",
//       price: 360,
//       rating: 65,
//       heartIcon: <FaRegHeart />,
//       eyeIcon: <FaEye />,
//       color: "green",
//       padding: "px-4 py-1",
     
//     },
//     {
//       id: 13,
//       image: "images/Product-5.svg",
//       title: "Small BookSelf",
//       price: 360,
//       rating: 65,
//       heartIcon: <FaRegHeart />,
//       eyeIcon: <FaEye />,
//       color: "green",
//       padding: "px-4 py-1",
     
//     },
//     {
//       id: 14,
//       image: "images/Product-6.svg",
//       title: "Small BookSelf",
//       price: 360,
//       rating: 65,
//       heartIcon: <FaRegHeart />,
//       eyeIcon: <FaEye />,
//       color: "green",
//       padding: "px-4 py-1",
     
//     },
//     {
//       id: 15,
//       image: "images/Product-7.svg",
//       title: "Small BookSelf",
//       price: 360,
//       rating: 65,
//       heartIcon: <FaRegHeart />,
//       eyeIcon: <FaEye />,
//       color: "green",
//       padding: "px-4 py-1",
     
//     },
//     {
//       id: 16,
//       image: "images/Product-8.svg",
//       title: "Small BookSelf",
//       price: 360,
//       rating: 65,
//       heartIcon: <FaRegHeart />,
//       eyeIcon: <FaEye />,
//       color: "green",
//       padding: "px-4 py-1",
     
//     },
//   ];
  